version: "3"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/var/www/webapp/src
      - ./public/:/var/www/webapp/public
      - ./scripts:/var/www/webapp/scripts
      - /var/www/webapp/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: always
    env_file: .env.dev
    networks:
      - webapp
    command: yarn start
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    env_file: .env.dev
    networks:
      - webapp
networks:
  webapp: {}
